# -*- coding: utf-8 -*-
"""Uso de  statsmodels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGuXnU0Bjl5qLleeFQO1opu3sL4Gzmil
"""

!pip install statsmodels

import statsmodels.api as sm
import pandas
from patsy import dmatrices

df = sm.datasets.get_rdataset("Guerry", "HistData").data

df

vars = ['Department', 'Lottery', 'Literacy', 'Wealth', 'Region']
df = df[vars] #Filtramos la tabla

df

df = df.dropna() #Eliminar filas con refistros vacios

df

df[-5:] #Consultr las ultimas 5 filas

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# %matplotlib inline
from statsmodels.tsa.exponential_smoothing.ets import ETSModel

plt.rcParams["figure.figsize"] = (12, 8)

oildata = [
    111.0091,
    130.8284,
    141.2871,
    154.2278,
    162.7409,
    192.1665,
    240.7997,
    304.2174,
    384.0046,
    429.6622,
    359.3169,
    437.2519,
    468.4008,
    424.4353,
    487.9794,
    509.8284,
    506.3473,
    340.1842,
    240.2589,
    219.0328,
    172.0747,
    252.5901,
    221.0711,
    276.5188,
    271.1480,
    342.6186,
    428.3558,
    442.3946,
    432.7851,
    437.2497,
    437.2092,
    445.3641,
    453.1950,
    454.4096,
    422.3789,
    456.0371,
    440.3866,
    425.1944,
    486.2052,
    500.4291,
    521.2759,
    508.9476,
    488.8889,
    509.8706,
    456.7229,
    473.8166,
    525.9509,
    549.8338,
    542.3405,
]
oil = pd.Series(oildata, index=pd.date_range("1965", "2013", freq="YS"))
oil.plot()
plt.ylabel("Annual oil production in Saudi Arabia (Mt)")

#Paso 1
model = ETSModel(oil) #Recogemos el modelo para los datos hitoricos
#Paso 2
fit = model.fit(maxiter=10000) #Hacer una cantidad de pruebas con las tuercas de ajustar

#De los datos de petroleo le asigna una etiqueta "data"
oil.plot(label="data")
fit.fittedvalues.plot(label="statsmodels fit") #Grafica la serie ajustada
plt.ylabel("Annual oil production in Saudi Arabia (Mt)") #Texto para el grafico

# obtained from R
params_R = [0.99989969, 0.11888177503085334, 0.80000197, 36.46466837, 34.72584983]
yhat = model.smooth(params_R).fittedvalues
yhat.plot(label="R fit", linestyle="--")

plt.legend()

#Paso 3: Ejecutar una proyección de la serie
fit.predict()

!python -m pip install prophet